package OWI535RobotArm;
import javax.swing.*;


/**
 * Create GUI interface to control the OWI-535 Robot Arm
 *
 * @author Craig Turner
 * 
 * @see <http://gampageek.blogspot.co.uk/2013/01/blog-post.html>
 */



public class RobotUserForm extends javax.swing.JFrame
{

    /**
     * Creates new form RobotUserForm
     */
    public RobotUserForm()
    {
        initComponents();//

    }
    static ArmCommunicator arm1 = new ArmCommunicator();

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButton3_ShoulderBack = new javax.swing.JButton();
        jButton4_ShoulderForward = new javax.swing.JButton();
        jButton5_ElbowBack = new javax.swing.JButton();
        jButton6_ElbowForward = new javax.swing.JButton();
        jButton1_BaseLeft = new javax.swing.JButton();
        jButton8_WristForward = new javax.swing.JButton();
        jButton9_WristBack = new javax.swing.JButton();
        jButton2_BaseRight = new javax.swing.JButton();
        jButton9_OpenGrip = new javax.swing.JButton();
        jButton8_CloseGrip = new javax.swing.JButton();
        jButton9_LightON = new javax.swing.JButton();
        jButton9_LightOFF = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OWI-535 Robot Arm");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 204, 255));
        setBounds(new java.awt.Rectangle(600, 300, 0, 0));

        jButton3_ShoulderBack.setText("Shoulder Back");
        jButton3_ShoulderBack.setMaximumSize(new java.awt.Dimension(100, 20));
        jButton3_ShoulderBack.setMinimumSize(new java.awt.Dimension(100, 20));
        jButton3_ShoulderBack.setPreferredSize(new java.awt.Dimension(110, 20));
        jButton3_ShoulderBack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3_ShoulderBackActionPerformed(evt);
            }
        });

        jButton4_ShoulderForward.setText("Shoulder Forward");
        jButton4_ShoulderForward.setMaximumSize(new java.awt.Dimension(100, 20));
        jButton4_ShoulderForward.setMinimumSize(new java.awt.Dimension(100, 20));
        jButton4_ShoulderForward.setPreferredSize(new java.awt.Dimension(110, 20));
        jButton4_ShoulderForward.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4_ShoulderForwardActionPerformed(evt);
            }
        });

        jButton5_ElbowBack.setText("Elbow Back");
        jButton5_ElbowBack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5_ElbowBackActionPerformed(evt);
            }
        });

        jButton6_ElbowForward.setText("Elbow Forward");
        jButton6_ElbowForward.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton6_ElbowForwardActionPerformed(evt);
            }
        });

        jButton1_BaseLeft.setText("Base Left");
        jButton1_BaseLeft.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1_BaseLeftActionPerformed(evt);
            }
        });

        jButton8_WristForward.setText("Wrist Forward");
        jButton8_WristForward.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton8_WristForwardActionPerformed(evt);
            }
        });

        jButton9_WristBack.setText("Wrist Back");
        jButton9_WristBack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton9_WristBackActionPerformed(evt);
            }
        });

        jButton2_BaseRight.setText("Base Right");
        jButton2_BaseRight.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2_BaseRightActionPerformed(evt);
            }
        });

        jButton9_OpenGrip.setText("Open Grip");
        jButton9_OpenGrip.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton9_OpenGrip.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton9_OpenGripActionPerformed(evt);
            }
        });

        jButton8_CloseGrip.setText("Close Grip");
        jButton8_CloseGrip.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton8_CloseGripActionPerformed(evt);
            }
        });

        jButton9_LightON.setText("Light ON");
        jButton9_LightON.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton9_LightON.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton9_LightONActionPerformed(evt);
            }
        });

        jButton9_LightOFF.setText("Light OFF");
        jButton9_LightOFF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton9_LightOFF.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton9_LightOFFActionPerformed(evt);
            }
        });

        menuBar.setAlignmentX(0.0F);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText(" ");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("ReadMe");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3_ShoulderBack, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jButton5_ElbowBack, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jButton9_WristBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4_ShoulderForward, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jButton6_ElbowForward, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jButton8_WristForward, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1_BaseLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2_BaseRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton9_OpenGrip, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8_CloseGrip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton9_LightON, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9_LightOFF, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_BaseLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2_BaseRight, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3_ShoulderBack, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jButton4_ShoulderForward, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5_ElbowBack, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6_ElbowForward, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9_WristBack, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8_WristForward, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9_OpenGrip, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8_CloseGrip, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9_LightOFF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9_LightON, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        arm1.close();
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed
    private void jButton3_ShoulderBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_ShoulderBackActionPerformed
        ArmCommunicator.doArmOp('j', arm1);
    }//GEN-LAST:event_jButton3_ShoulderBackActionPerformed

    private void jButton4_ShoulderForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_ShoulderForwardActionPerformed
        ArmCommunicator.doArmOp('u', arm1);
    }//GEN-LAST:event_jButton4_ShoulderForwardActionPerformed

    private void jButton5_ElbowBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_ElbowBackActionPerformed
        ArmCommunicator.doArmOp('f', arm1);
    }//GEN-LAST:event_jButton5_ElbowBackActionPerformed

    private void jButton6_ElbowForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6_ElbowForwardActionPerformed
        ArmCommunicator.doArmOp('r', arm1);
    }//GEN-LAST:event_jButton6_ElbowForwardActionPerformed

    private void jButton1_BaseLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_BaseLeftActionPerformed
        ArmCommunicator.doArmOp('k', arm1);
    }//GEN-LAST:event_jButton1_BaseLeftActionPerformed

    private void jButton8_WristForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8_WristForwardActionPerformed
        ArmCommunicator.doArmOp('e', arm1);
    }//GEN-LAST:event_jButton8_WristForwardActionPerformed

    private void jButton9_WristBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9_WristBackActionPerformed
        ArmCommunicator.doArmOp('d', arm1);
    }//GEN-LAST:event_jButton9_WristBackActionPerformed

    private void jButton8_CloseGripActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton8_CloseGripActionPerformed
    {//GEN-HEADEREND:event_jButton8_CloseGripActionPerformed
        ArmCommunicator.doArmOp('w', arm1);
    }//GEN-LAST:event_jButton8_CloseGripActionPerformed

    private void jButton9_OpenGripActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton9_OpenGripActionPerformed
    {//GEN-HEADEREND:event_jButton9_OpenGripActionPerformed
        ArmCommunicator.doArmOp('s', arm1);
    }//GEN-LAST:event_jButton9_OpenGripActionPerformed

    private void jButton9_LightONActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton9_LightONActionPerformed
    {//GEN-HEADEREND:event_jButton9_LightONActionPerformed
        ArmCommunicator.doArmOp('l', arm1);
    }//GEN-LAST:event_jButton9_LightONActionPerformed

    private void jButton9_LightOFFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton9_LightOFFActionPerformed
    {//GEN-HEADEREND:event_jButton9_LightOFFActionPerformed
        ArmCommunicator.doArmOp('p', arm1);
    }//GEN-LAST:event_jButton9_LightOFFActionPerformed

    private void jButton2_BaseRightActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2_BaseRightActionPerformed
    {//GEN-HEADEREND:event_jButton2_BaseRightActionPerformed
        ArmCommunicator.doArmOp('i', arm1);
    }//GEN-LAST:event_jButton2_BaseRightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) // MAIN ****************************
    {

        //Run FORM and make visible:     

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RobotUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RobotUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RobotUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RobotUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new RobotUserForm().setVisible(true);
            }
        });
    }// end of main************************************************************
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton1_BaseLeft;
    private javax.swing.JButton jButton2_BaseRight;
    private javax.swing.JButton jButton3_ShoulderBack;
    private javax.swing.JButton jButton4_ShoulderForward;
    private javax.swing.JButton jButton5_ElbowBack;
    private javax.swing.JButton jButton6_ElbowForward;
    private javax.swing.JButton jButton8_CloseGrip;
    private javax.swing.JButton jButton8_WristForward;
    private javax.swing.JButton jButton9_LightOFF;
    private javax.swing.JButton jButton9_LightON;
    private javax.swing.JButton jButton9_OpenGrip;
    private javax.swing.JButton jButton9_WristBack;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
